### ISSUE TITLE
大佬们求个联系方式！

### ISSUE THREAD

**Issue by nebnoob** [yxhpy/Vue3-Magic-Generator#3]
对这个项目非常感兴趣!

**Comment by yxhpy** [comment]
你想了解什么呢？

**Comment by nebnoob** [comment]
> 你想了解什么呢？
我想先部署到本地看看，因为我有很多gpt4的模型和接口key，大佬需要的话我也可以提供

**Comment by yxhpy** [comment]
是想看在本地本怎么部署是吧，这个在日程中了，后续会出教程。上班哈，只有晚上有时间。

**Comment by yxhpy** [comment]
最好现在可以自行研究一下，东西还是有点多，视频讲的比较粗
